// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuneaPianoPSP;

#nullable disable

namespace TuneaPianoPSP.Migrations
{
    [DbContext(typeof(TuneaPianoDbContext))]
    [Migration("20240311204932_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("Genresid")
                        .HasColumnType("integer");

                    b.Property<int>("Songsid")
                        .HasColumnType("integer");

                    b.HasKey("Genresid", "Songsid");

                    b.HasIndex("Songsid");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.Artist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 26,
                            bio = "Big & Rich is an American country music duo composed of Big Kenny and John Rich, both of whom are songwriters, vocalists, and guitarists.",
                            name = "Big and Rich"
                        },
                        new
                        {
                            id = 2,
                            age = 55,
                            bio = "Having spent last spring and early summer with his taking-it-to-the-roots I Go Back 2023 Tour of those arenas and markets where he rose to major headlining status, the only country artist to be on Billboard’s Top 10 Touring Artists of the Last 25 Years for the past 14 years is bringing old friends and new to 18 full-scale stadiums with a few more major surprises to come.",
                            name = "Kenny Chesney"
                        },
                        new
                        {
                            id = 3,
                            age = 34,
                            bio = "On December 3, 1990, Enigma released its debut album “MCMXC a.D.”. It was the beginning of an exceptional global success story. A quarter-century later Enigma is launching “Enigma Moments” - an online event to commemorate the project’s 25th anniversary together with you, loyal Enigma fans.",
                            name = "Enigma"
                        },
                        new
                        {
                            id = 4,
                            age = 77,
                            bio = "Benjamin David Goodman (May 30, 1909 – June 13, 1986) was an American clarinetist and bandleader known as the \"King of Swing\".",
                            name = "Benny Goodman"
                        });
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Country"
                        },
                        new
                        {
                            id = 2,
                            description = "Pop"
                        },
                        new
                        {
                            id = 3,
                            description = "Jazz"
                        },
                        new
                        {
                            id = 4,
                            description = "Blues"
                        },
                        new
                        {
                            id = 5,
                            description = "R & B Soul"
                        });
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.Song", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("album")
                        .HasColumnType("text");

                    b.Property<int?>("artistId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("length")
                        .HasColumnType("numeric");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("artistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            album = "Horse of a Different Color",
                            artistId = 0,
                            length = 180m,
                            title = "Save a Horse (Ride a Cowboy)"
                        },
                        new
                        {
                            id = 2,
                            album = "No Shoes nation",
                            artistId = 1,
                            length = 183m,
                            title = "Take Her Home"
                        },
                        new
                        {
                            id = 3,
                            album = "The Fall of a Rebel Angel",
                            artistId = 2,
                            length = 339m,
                            title = "The Omego Point"
                        },
                        new
                        {
                            id = 4,
                            album = "The Essential Benny Goodman(Remastered)",
                            artistId = 3,
                            length = 540m,
                            title = "Sing, Sing, Sing"
                        });
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.SongGenre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("genreId")
                        .HasColumnType("integer");

                    b.Property<int>("songId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("SongGenres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            genreId = 0,
                            songId = 0
                        },
                        new
                        {
                            id = 2,
                            genreId = 0,
                            songId = 1
                        },
                        new
                        {
                            id = 3,
                            genreId = 1,
                            songId = 2
                        },
                        new
                        {
                            id = 4,
                            genreId = 2,
                            songId = 3
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("TuneaPianoPSP.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("Genresid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuneaPianoPSP.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("Songsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.Song", b =>
                {
                    b.HasOne("TuneaPianoPSP.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("artistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TuneaPianoPSP.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
